//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdNo { get; set; }
        public Nullable<int> ShNo { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public string AdTitle { get; set; }
        public System.DateTime AdApplyDate { get; set; }
        public System.DateTime AdStartDate { get; set; }
        public System.DateTime AdTime { get; set; }
        public int AdPrice { get; set; }
        public string AdPic { get; set; }
        public string AdURL { get; set; }
        public string AdCheckState { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
