//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberList()
        {
            this.ShopOrder = new HashSet<ShopOrder>();
        }
    
        public int OrderNo { get; set; }
        public Nullable<int> MemNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrder> ShopOrder { get; set; }
    }
}
