//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Advertisement = new HashSet<Advertisement>();
            this.FavoriteShopList = new HashSet<FavoriteShopList>();
            this.Product = new HashSet<Product>();
            this.ProductClass = new HashSet<ProductClass>();
            this.ShopOrder = new HashSet<ShopOrder>();
        }
    
        public int ShNo { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public string ShThePic { get; set; }
        public string ShName { get; set; }
        public string ShClassNo { get; set; }
        public string ShAccount { get; set; }
        public string ShPwd { get; set; }
        public string ShBoss { get; set; }
        public string ShContact { get; set; }
        public string ShAddress { get; set; }
        public string ShTel { get; set; }
        public string ShEmail { get; set; }
        public string ShAbout { get; set; }
        public string ShLogoPic { get; set; }
        public string ShUrl { get; set; }
        public string ShAdState { get; set; }
        public string ShAdTitle { get; set; }
        public string ShAdPic { get; set; }
        public string ShPopShop { get; set; }
        public string ShCheckState { get; set; }
        public Nullable<System.DateTime> ShStartDate { get; set; }
        public Nullable<System.DateTime> ShEndDate { get; set; }
        public Nullable<System.DateTime> ShCheckDate { get; set; }
        public string ShPwdState { get; set; }
        public Nullable<System.DateTime> ShStopRightStartDate { get; set; }
        public Nullable<System.DateTime> ShStopRightEnddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteShopList> FavoriteShopList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductClass> ProductClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrder> ShopOrder { get; set; }
    }
}
