//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllShowMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllShowEntities : DbContext
    {
        public AllShowEntities()
            : base("name=AllShowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<AuthorityFunction> AuthorityFunction { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FavoriteShopList> FavoriteShopList { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberList> MemberList { get; set; }
        public virtual DbSet<OrderList> OrderList { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductClass> ProductClass { get; set; }
        public virtual DbSet<ShClass> ShClass { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopOrder> ShopOrder { get; set; }
    }
}
